coinhub/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='home'),
    path(
        'create-crypto-list/',
        views.create_crypto_list,
        name='create_crypto_list'
    ),
    path('markets/', views.markets, name='markets'),
    path(
        'crypto-search-results/',
        views.crypto_search_results,
        name='crypto_search_results'
    ),
    path('get_market_data/', views.get_market_data, name='get_market_data'),
    path(
        'get_popular_crypto/',
        views.get_popular_crypto,
        name='get_popular_crypto'
    ),
    path('crypto/<str:symbol>/', views.crypto_details, name='crypto_details'),
    path(
        'crypto_detail_price_data_from_api/<str:time_period>/<str:symbol>/',
        views.crypto_detail_price_data_from_api,
        name='crypto_detail_price_data_from_api'
         ),
    path(
        'get_crypto_detail_json/',
        views.get_crypto_detail_json,
        name='get_crypto_detail_json'
    ),
    path('trade/', views.trade_page, name='trade'),
    path('deposit_euro/', views.deposit_page, name='deposit_page'),
    path('deposit/<str:amount>/', views.deposit, name='deposit'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('get_user_data/', views.get_user_data, name='get_user_data'),
    path(
        'trading_pair/<str:symbol>/', views.trading_pair, name='trading_pair'
    ),
    path(
        'get_trading_pair_data/<str:symbol>/',
        views.get_trading_pair_data,
        name='get_trading_pair_data'),
    path(
        'get_transaction_data/',
        views.get_transaction_data,
        name='get_transaction_data'
    ),
    path(
        'delete_transaction/<str:transaction_uuid>/<str:symbol>',
        views.delete_transaction,
        name='delete_transaction'
    ),
    path(
        'buy_sell_order/<str:time_placed>/<str:symbol>/<str:orderType>/'
        '<str:bsType>/<str:price>/<str:amount>/<str:total>/',
        views.buy_sell_order,
        name='buy_sell_order'
    ),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_view, name='contact'),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from contact.views import contact_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coinhub.urls')),
    path('accounts/', include('allauth.urls')),
    path('contact/', contact_view, name='contact'),
    path('profile/', include('profileapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

profileapp/urls.py
from django.urls import path
from . import views

app_name = 'profileapp'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('edit', views.edit_profile, name='edit_profile'),
    path('edit_profile_picture', views.edit_profile_picture, name='edit_profile_picture'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    ISSUE_CHOICES = [
        ('deposit', 'Depositing Money'),
        ('trading', 'Trading Coins'),
        ('assets', 'Assets not showing in my portfolio'),
        ('other', 'Other'),
    ]
    name = models.CharField(max_length=100)
    email = models.EmailField()
    issue = models.CharField(max_length=255, choices=ISSUE_CHOICES, default='other')
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'issue', 'message']

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
import os
from django.core.mail import send_mail
from django.contrib import messages


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            send_contact_email(form.cleaned_data)
            messages.success(request, 'Your message has been sent successfully.', extra_tags='notification')
            return redirect('contact')

    else:
        form = ContactForm()
    
    return render(request, 'contact.html', {'form': form})


def send_contact_email(data):
    subject = f'CoinHub Message - Issue: {data["issue"]}'
    message = f"Name: {data['name']}\nEmail: {data['email']}\n\n{data['message']}"
    from_email = os.environ.get('HOST_EMAIL')
    to_email = [os.environ.get('CONTACT_TO_EMAIL')]
    send_mail(subject, message, from_email, to_email)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <!-- Cropper -->
    {% if edit_profile_picture %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cropperjs@1.5.12/dist/cropper.min.css">
    <script src="https://cdn.jsdelivr.net/npm/cropperjs@1.5.12/dist/cropper.min.js"></script>
    {% endif %}

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>CoinHub</title>
</head>
<body>
    <!-- Header Logo, Nav Bar and Social Links -->
    <header>
        <div class="header-container">
            <!-- Logo -->
            <div class="logo-container">
                <a href="{% url 'home' %}" class="logo">
                    
                    <div class="logo-img-container">
                        <img src="https://res.cloudinary.com/dzwyiggcp/image/upload/v1684587917/CI_PP4_COINHUB/logo/kgrdqh5emmauutm2qtn5.png" alt="CoinHub Logo"
                            class="logo-img">
                    </div>
                    
                    <div class="logo-text">CoinHub</div>
                </a>
            </div>
            <!-- Nav Bar -->
            <nav class="nav-bar">
                <ul class="nav-menu">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a href="{% url 'deposit_page' %}" class="nav-link">Deposit</a>
                        {% else %}
                        <a href="{% url 'account_login' %}" class="nav-link">Buy Crypto</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'markets' %}" class="nav-link">Markets</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'trade' %}" class="nav-link">Trade</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'contact' %}" class="nav-link">Contact</a>
                    </li>
                </ul>
                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>
            </nav>
            <!-- Account Buttons -->
            <div class="account-login-container">
                <div class="account-login-btns-container">
                    {% if user.is_authenticated %}
                    <div class="account-profile-container">
                        <div class="account-profile-img-container">
                            {% if member_profile %}
                            <img src="{{ member_profile.profile_image }}" alt="Profile Picture" class="account-profile-img img-100a">
                            {% else %}
                            <img src="https://res.cloudinary.com/dzwyiggcp/image/upload/v1689692743/MREEA/default-profile-pic_yp9kzz.png" alt="Profile Picture" class="account-profile-img img-100a">
                            {% endif %}
                        </div>
                        <div class="profile-btns-container content-container">
                            <a href="{% url 'profileapp:profile' %}" class="profile-btn-link">
                                View Profile
                            </a>
                            <a href="{% url 'portfolio' %}" class="profile-btn-link">
                                Portfolio
                            </a>
                            <a href="{% url 'account_logout' %}" class="btn logout-btn">
                                Log Out
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="account-profile-container">
                        <div class="account-profile-img-container not-logged-in">
                            <img src="https://res.cloudinary.com/dzwyiggcp/image/upload/v1690486403/log-in_qo9dg3.png" alt="Profile Picture" class="account-profile-img img-100a">
                        </div>
                        <div class="profile-btns-container content-container login-register-container">
                            <a href="{% url 'account_login' %}" class="dark-text">
                                Login
                            </a>
                            <a href="{% url 'account_signup' %}" class="btn register-btn">
                                Register
                            </a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    <div class="notification-container content-container-rows">
        <div class="notification-message white-text"></div>
    </div>
    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <footer>
        <div class="footer-container">
            <!-- Copyright -->
            <div class="copyright">
                © Copyrights 2023
                CoinHub
            </div>
            <!-- Disclaimer -->
            <div class="disclaimer">
                *Disclaimer: This website is for educational purposes only; it does not facilitate real cryptocurrency transactions. Exercise caution and seek professional advice for actual investments.
            </div>
            <!-- Footer Logo -->
            <div class="footer-logo-img-container">
                <img src="https://res.cloudinary.com/dzwyiggcp/image/upload/v1685017432/CI_PP4_COINHUB/logo/ny7oezfhfqzlbtwibcu6.png" alt="CoinHub Logo"
                    class="footer-logo">
            </div>
        </div>
    </footer>

    

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/5821df7d40.js" crossorigin="anonymous"></script>

    <script src="{% static 'js/nav-menu.js' %}"></script>
    <script src="{% static 'js/notification.js' %}"></script>
    {% block js %}
    {% endblock %}
    
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="section contact-form-section light-gray-1">
    <div class="section-contianer content-container gp-20">
        <h2 class="heading">Contact Us</h2>
        <div class="content-container contact-form-container">
            <form method="post" class="contact-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn">Submit</button>
            </form>
        </div>
    </div>
</section>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

{% block js %}


{% endblock %}

templates/deposit.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="deposit-section section content-container gp-50">
    <h2 class="sub-heading-3">Deposit</h2>
    <div class="deposit-card content-container">
        <div class="deposit-card-balance text-gd-2">Current Balance: €<span class="euro-balance">{{ euro }}</span></div>
        <div class="deposit-card-wrapper">
            <div class="deposit-form-wrapper">
                <form method="post" class="deposit-form content-container gp-10" novalidate autocomplete="off">
                    {% csrf_token %}
                    <div class="deposit-form-input-container content-container">
                        <label class="dark-text" for="cardholder">Cardholder Name:</label>
                        <div class="deposit-input-wrapper">
                            <input class="deposit-form-input cardholder-input" type="text" id="cardholder" name="cardholder" required>
                        </div>
                    </div>
                    <div class="deposit-form-input-container content-container">
                        <label class="dark-text" for="cardnumber">Card Number:</label>
                        <div class="deposit-input-wrapper">
                            <input class="deposit-form-input cardnumber-input" type="text" id="cardnumber" name="cardnumber" required>
                        </div>
                    </div>
                    <div class="expire-cvv-container content-container-rows">
                        <div class="deposit-form-input-container content-container">
                            <label class="dark-text" for="expiration">Expire Date:</label>
                            <div class="deposit-input-wrapper">
                                <input class="deposit-form-input expiration-input" type="text" id="expiration" name="expiration" placeholder="MM/YYYY" required>
                            </div>
                        </div>
                        <div class="deposit-form-input-container content-container">
                            <label class="dark-text" for="cvv">CVV:</label>
                            <div class="deposit-input-wrapper">
                                <input class="deposit-form-input cvv-input" type="text" id="cvv" name="cvv" required>
                            </div>
                        </div>
                    </div>
                    <div class="deposit-form-input-container content-container deposit-form-amount-input-container">
                        <label class="dark-text" for="amount">Amount: (limit: 1000000)</label>
                        <div class="deposit-input-wrapper">
                            <input class="deposit-form-input amount-input" type="text" id="amount" name="amount" required>
                            <div class="dark-text euro-symbol">€</div>
                        </div>
                    </div>
                    <div class="deposit-form-input-container"></div>
                    <button type="submit" class="btn deposit-btn">Deposit</button>
                </form>
            </div>
            <div class="balance-container content-container gp-20">
                <div class="balance-message dark-text">You have successfully deposited €<span class="deposit-amount"></span> into your account!</div>
                <div class="blance-message dark-text">Your Balance is: €<span class="euro-balance"></span></div>
                <a href="{% url 'deposit_page' %}" class="btn add-more-btn">Add More</a>
            </div>
            <div class="loading-icon-container"></div>
        </div>
    </div>
</section>

{% endblock %}

{% block js %}

<script src="{% static 'js/deposit.js' %}"></script>

{% endblock %}

templates/markets.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="crypto-search-section section light-gray-1">
    <div class="content-container gp-50">
        <div class="heading-container content-container gp-10">
            <h2 class="heading-3 dark-text">Find your cryptocurrency</h2>
            <div class="sub-heading-3 dark-text text-gd-2">In the past 24 hours the market is <span class="market-change">...</span></div>
        </div>
        
        <div class="content-container search-container gp-20">
            <form class="crypto-search-form" method="GET">
                <div class="input-container">
                    <input type="text" autocomplete="off" class="crypto-search-input" name="query" placeholder="Search for an asset">
                    <span class="search-icon"><i class="fas fa-search"></i></span>
                    <span class="close-icon"><i class="fa-solid fa-xmark"></i></span>
                </div>
            </form>

            <div class="crypto-search-results content-container"></div>
        </div>
    </div>
</section>

<section class="trending-crypto-section section light-gray-1 markets-section">
    <div class="content-container gp-50 section-container">
        <div class="heading-container content-container gp-10">
            <h2 class="heading-3 dark-text">Explore what's hot in the crypto economy</h2>
            <div class="sub-heading-3 dark-text text-gd-2">Here's some popular, top gainers and top losers in the last 24 hours</div>
        </div>

        <div class="trending-crypto-container content-container-rows w-100">
            <div class="content-container gp-20 w-33">
                <div class="sub-heading-3 dark-text text-gd-2">Popular Crypto</div>
                <div class="trending-crypto-card content-container gp-20 w-100 p-20">
                    {% for crypto in popular_crypto %}
                    <div class="trending-crypto-item content-container-rows w-100">
                        <a href="{% url 'crypto_details' crypto.symbol %}" class="trending-icon-name-symbol content-container-rows gp-10">
                            <div class="crypto-icon-container trending-icon-container">
                                <img src="{{ crypto.icon }}" alt="{{ crypto.name }} icon" class="crypto-icon">
                            </div>
                            <div class="trending-name-symbol content-container">
                                <div class="crypto-symbol trending-crypto-symbol">{{ crypto.symbol }}</div>
                            </div>
                        </a>
                        <div class="trending-crypto-price-container">
                            <div class="crypto-price trending-crypto-price">{{ crypto.price }}</div>
                        </div>
                        <div class="crypto-change trending-crypto-change">{{ crypto.change }}%</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="content-container gp-20 w-33">
                <div class="sub-heading-3 dark-text text-gd-2">Top Gainers</div>
                <div class="trending-crypto-card content-container gp-20 w-100 p-20">
                    {% for crypto in top_gainers %}
                    <div class="trending-crypto-item content-container-rows w-100">
                        <a href="{% url 'crypto_details' crypto.symbol %}" class="trending-icon-name-symbol content-container-rows gp-10">
                            <div class="crypto-icon-container trending-icon-container">
                                <img src="{{ crypto.icon }}" alt="{{ crypto.name }} icon" class="crypto-icon">
                            </div>
                            <div class="trending-name-symbol content-container">
                                <div class="crypto-symbol trending-crypto-symbol">{{ crypto.symbol }}</div>
                            </div>
                        </a>
                        <div class="trending-crypto-price-container">
                            <div class="crypto-price trending-crypto-price">{{ crypto.price }}</div>
                        </div>
                        <div class="crypto-change trending-crypto-change">{{ crypto.change }}%</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="content-container gp-20 w-33">
                <div class="sub-heading-3 dark-text text-gd-2">Top Losers</div>
                <div class="trending-crypto-card content-container gp-20 w-100">
                    {% for crypto in top_losers %}
                    <div class="trending-crypto-item content-container-rows w-100">
                        <a href="{% url 'crypto_details' crypto.symbol %}" class="trending-icon-name-symbol content-container-rows gp-10">
                            <div class="crypto-icon-container trending-icon-container">
                                <img src="{{ crypto.icon }}" alt="{{ crypto.name }} icon" class="crypto-icon">
                            </div>
                            <div class="trending-name-symbol content-container">
                                <div class="crypto-symbol trending-crypto-symbol">{{ crypto.symbol }}</div>
                            </div>
                        </a>
                        <div class="trending-crypto-price-container">
                            <div class="crypto-price trending-crypto-price">{{ crypto.price }}</div>
                        </div>
                        <div class="crypto-change trending-crypto-change">{{ crypto.change }}%</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Crypto Markets List -->
<section class="crypto-list-markets-section section light-gray-1 markets-section">
    <div class="section-container crypto-list-markets-container content-container gp-50">
        <div class="heading-container content-container gp-10">
            <h2 class="heading-3 dark-text">Crypto Markets</h2>
            <div class="sort-btns-container content-container-rows">

            </div>
        </div>
        <div class="content-container w-100 gp-10">
            <!-- Markets List -->
            <div class="markets-table-wrapper table-wrapper w-100">
                <table class="crypto-list-home-table crypto-list-markets-table w-100">
                    <thead>
                        <tr>
                            <th class="crypto-name-symbol-heading">Name</th>
                            <th class="crypto-price-heading">Price</th>
                            <th class="crypto-change">Change</th>
                            <th class="crypto-chart">Chart</th>
                            <th class="crypto-market-cap-heading">Market Cap</th>
                            <th class="crypto-volume-heading">Volume (24h)</th>
                            <th class="crypto-trade">Trade</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for crypto in cryptocurrencies %}
                            <tr>
                                <td class="crypto-name-symbol">
                                    <a href="{% url 'crypto_details' crypto.symbol %}"  class="crypto-name-symbol-wrapper">
                                        <div class="crypto-icon-container">
                                            <img src="{{ crypto.icon }}" alt="{{ crypto.name }} Icon" class="crypto-icon">
                                        </div>
                                        <div class="crypto-details">
                                            <div class="crypto-name">{{ crypto.name }}</div>
                                            <div class="crypto-symbol">{{ crypto.symbol }}</div>
                                        </div>
                                    </a>
                                </td>
                                <td class="crypto-price">{{ crypto.price }}</td>
                                <td class="crypto-change">{{ crypto.change }}%</td>
                                <td class="crypto-chart">
                                    <div class="table-content-wrapper w-100">
                                        <canvas class="price-sparkline"></canvas>
                                    </div>
                                </td>
                                <td class="crypto-market-cap">{{ crypto.market_cap }}</td>
                                <td class="crypto-volume">{{ crypto.volume }}</td>
                                <td class="crypto-trade">
                                    <div class="table-content-wrapper w-100">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'trading_pair' symbol=crypto.symbol %}" class="buy-btn btn">Buy</a>
                                        {% else %}
                                        <a href="{% url 'account_signup' %}" class="buy-btn btn">Buy</a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/crypto-search.js' %}"></script>
<script src="{% static 'js/crypto-list.js' %}"></script>
<script src="{% static 'js/format-numbers.js' %}"></script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="section member-profile-section">
    <div class="section-container member-profile-section-container">
        <div class="profile-card content-container profile-picture-card">
            <div class="profile-picture-col-container content-container">
                <div class="profile-img-container">
                    <img src="{{ member_profile.profile_image.url }}" alt="{{ member_profile.first_name }} Profile Image" class="profile-img img-100a">
                    <a href="{% url 'profileapp:edit_profile_picture' %}" class="edit-picture-btn">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <div class="edit-picture-overlay"></div>
                </div>
                <div class="content-container gp-20 first-last-name-pp">
                    {% if member_profile.first_name %}
                    <h2 class="dark-text">First Name: {{ member_profile.first_name }}</h2>
                    {% else %}
                    <div class="dark-text nothing-displayed">First Name: *Nothing Displayed</div>
                    {% endif %}
                    {% if member_profile.last_name %}
                    <div class="dark-text">Last Name: {{ member_profile.last_name }}</div>
                    {% else %}
                    <div class="dark-text nothing-displayed">Last Name: *Nothing Displayed</div>
                    {% endif %}
                </div>
                
                <a href="{% url 'profileapp:edit_profile' %}" class="btn">Edit Profile</a>
            </div>
        </div>
    </div>
</section>

{% if edit_profile %}

<section class="edit-profile-section section">
    <div class="edit-profile-card content-container">
        <div class="edit-profile-form-container content-container gp-20">
            <h2 class="heading dark-text">Edit Profile </h2>
            <form method="post" class="edit-profile-form">
                {% csrf_token %}
                {% if edit_profile_picture %}
                <div class="edit-profile-picture-form-wrapper content-container">
                    {{ form }}
                    <input type="hidden" name="croppedImageData" id="croppedImageData">
                </div>
                <div class="edit-pp-container content-container">
                    <div class="edit-pp-input-container">
                        <input type="file" id="imageInput" accept="image/*">
                    </div>

                    <div class="clear-pp-container content-container-rows">
                        <div class="clear-pp-text">Clear</div>
                        <input type="checkbox" id="clearPP">
                    </div>

                    <div class="sub-heading dark-text">Crop</div>
                    <div class="crop-pp-img-container">
                        <img id="croppedImage" src="{{ member_profile.profile_image }}" alt="Cropped Image Preview" class="crop-image">
                    </div>

                    <input type="submit" name="cancel" value="&#10006;" class="form-close-btn">

                    <div class="btn preview-btn">Preview</div>
                </div>
                <div class="preview-pp-container content-container">
                    <div class="sub-heading dark-text">Preview</div>
                    <div class="preview-pp-img-container content-container">
                        <img id="previewImage" src="{{ member_profile.profile_image }}" alt="Cropped Image Preview" class="img-100a">
                    </div>

                    <div class="create-event-form-btns-container content-container-rows">
                        <input type="submit" name="cancel" value="Cancel" class="form-cancel-btn btn">
                        <input type="submit" value="Save" class="btn form-save-btn">
                    </div>
                    <input type="submit" name="cancel" value="&#10006;" class="form-close-btn">
                </div>
                {% else %}
                {{ form.as_p }}
                <div class="create-event-form-btns-container content-container-rows">
                    <input type="submit" name="cancel" value="Cancel" class="form-cancel-btn btn">
                    <input type="submit" value="Save" class="btn form-save-btn">
                </div>
                <input type="submit" name="cancel" value="&#10006;" class="form-close-btn">
                {% endif %}
            </form>
        </div>
    </div>
</section>

{% endif %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

{% block js %}

{% if edit_profile_picture %}

<script src="{% static 'js/crop-pp.js' %}"></script>
<script src="{% static 'js/notification.js' %}"></script>

{% endif %}


{% endblock %}